### ISSUE TITLE
Hose Collision

### ISSUE THREAD

**Issue by JiminyKroket** [Mr-RageMonster/ImprovedFireStations#1]
So i installed the version with no hoses, and it seems the collisions for the hoses are still in game.

**Comment by 398-Studios** [comment]
When it was tested and released and there was nothing wrong with the collisions. Also make sure that you have no other scripts installed that could conflict with the collisions of this script

**Comment by JiminyKroket** [comment]
Hmm well if it is fully functioning for others then I'll close the issue, I'm sorry. It seems to only be Davis station but I'll try to figure it out or deal with it
